### ISSUE TITLE
Properly grab root heap

### ISSUE THREAD

**Issue by shadowninja108** [shadowninja108/Starlight#10]
Currently all data must be allocated in the .data/bss segments. @OatmealDome has a workaround by getting the ResMgr's heap, but it's not ideal. The game's own new operator should be operational once a proper heap can be grabbed.

**Comment by 3096** [comment]
What would you consider as a "proper heap"?

**Comment by OatmealDome** [comment]
I assume not using one of the game's heaps, but making a dedicated heap just for Starlight

**Comment by 3096** [comment]
Alternatively, we could override operator new to use malloc.

**Comment by khang06** [comment]
splatoon 2 malloc or glib malloc? glib malloc fucks things up on games

**Comment by 3096** [comment]
splatoon 2 malloc obv
