### ISSUE TITLE
Trampoline?

### ISSUE THREAD

**Issue by jonahnm** [shadowninja108/Starlight#16]
(backing up a function so you can call it within the replaced function in case you have an if statement to not do something and you want to call the original function)

**Comment by ghost** [comment]
Skyline provides that utility with live hooks, as starlight is using static linking you can't really backup anything your replace with a code patch so you have to either handle that yourself or use live patching with skyline

**Comment by jonahnm** [comment]
> Skyline provides that utility with live hooks, as starlight is using static linking you can't really backup anything your replace with a code patch so you have to either handle that yourself or use live patching with skyline

decided to use exlaunch anyways as shadow switch to using it and starlight is kind of broken.

**Comment by nvnprogram** [comment]
Shadow is using skyline for splatoon 2, not exlaunch. Exlaunch is better than skyline in some ways, but newer doesn’t mean better in all ways. Skyline is better  to run with games and create game specific modifications while exlaunch is better for universal plugins, so in your case you should use skyline.

**Comment by shadowninja108** [comment]
Idk what you’re talking about. I’m using exlaunch. Anyways, starlight was always meant to be achieved with static patching, so there’s no way to provide trampolines. Also, I don’t plan on maintaining this project anyways.
